var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(f,c,e){return f==a&&"q"==c&&e==b}}));return!0===b.q}catch(f){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){a!=Array.prototype&&a!=Object.prototype&&(a[b]=f.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill=function(a,b,f,c){if(b){f=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in f||(f[e]={});f=f[e]}a=a[a.length-1];c=f[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),d=Object.seal({}),h=new a([[b,2],[d,3]]);if(2!=h.get(b)||3!=h.get(d))return!1;h.delete(b);h.set(d,4);return!h.has(b)&&4==h.get(d)}catch(l){return!1}}function f(a){$jscomp.owns(a,e)||$jscomp.defineProperty(a,e,{value:{}})}function c(a){var d=Object[a];d&&(Object[a]=function(a){f(a);return d(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;
var e="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var k=0,g=function(a){this.id_=(k+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};g.prototype.set=function(a,d){f(a);if(!$jscomp.owns(a,e))throw Error("WeakMap key fail: "+a);a[e][this.id_]=d;return this};g.prototype.get=function(a){return $jscomp.owns(a,e)?a[e][this.id_]:void 0};g.prototype.has=
function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)};g.prototype.delete=function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)?delete a[e][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),b=new a($jscomp.makeIterator([[d,"s"]]));if("s"!=b.get(d)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var l=b.entries(),c=l.next();if(c.done||c.value[0]!=d||"s"!=c.value[1])return!1;c=l.next();return c.done||4!=c.value[0].x||"t"!=c.value[1]||!l.next().done?!1:!0}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var f=new WeakMap,c=function(a){this.data_={};this.head_=g();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)d=d.value,this.set(d[0],d[1])}};c.prototype.set=function(a,b){var d=e(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=b:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:a,value:b},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};c.prototype.delete=function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};c.prototype.has=function(a){return!!e(this,a).entry};
c.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};c.prototype.entries=function(){return k(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return k(this,function(a){return a.key})};c.prototype.values=function(){return k(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var e=function(a,b){var c=b&&typeof b;"object"==
c||"function"==c?f.has(b)?c=f.get(b):(c=""+ ++m,f.set(b,c)):c="p_"+b;var d=a.data_[c];if(d&&$jscomp.owns(a.data_,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||b===e.key)return{id:c,list:d,index:a,entry:e}}return{id:c,list:d,index:-1,entry:void 0}},k=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},g=function(){var a={};return a.previous=
a.next=a.head=a},m=0;return c},"es6","es3");var VERSION={major:0,minor:3};var LOG=["ERROR","WARN","INFO","DEBUG","VERBOSE"],gLogLevel=3,gLogTimestamp=!0;function _log(a,b){var f=gLogTimestamp?(new Date).toISOString():"";a<gLogLevel&&console.log(f+"[WEBUI]["+LOG[a]+"]"+b)}var mlog={e:function(a){_log(0,a)},w:function(a){_log(1,a)},i:function(a){_log(2,a)},d:function(a){_log(3,a)},v:function(a){_log(4,a)},setLevel:function(a){gLogLevel=a}};var gSN_c2s=0,gSN_s2c=0,gRequestQueue_c2s=new Map,gRequestQueue_s2c=new Map,gWS_c2s,gWS_s2c,gWSHost="ws://127.0.0.1",gWSPort=3697,protocol_c2s="mstar-webui-c2s",protocol_s2c="mstar-webui-s2c",gCallback=null;function WS_C2S_OnOpen(a){mlog.i("[WS_C2S] opened")}function WS_S2C_OnOpen(a){mlog.i("[WS_S2C] opened")}function WS_C2S_OnClose(a){mlog.i("[WS_C2S] closed");null!=gCallback&&(gCallback(!1),gCallback=null)}
function WS_S2C_OnClose(a){mlog.i("[WS_S2C] closed");null!=gCallback&&(gCallback(!1),gCallback=null)}function WS_C2S_OnError(a){mlog.e("[WS_C2S] on error");null!=gCallback&&(gCallback(!1),gCallback=null)}function WS_S2C_OnError(a){mlog.e("[WS_S2C] on error");null!=gCallback&&(gCallback(!1),gCallback=null)}
function WS_C2S_OnMessage(a){mlog.i("[WS_C2S] on message");mlog.d("[WS_C2S] raw data: "+a.data);a=JSON.parse(a.data);gRequestQueue_c2s.has(a.sn)&&(gRequestQueue_c2s.get(a.sn)(a.args),gRequestQueue_c2s.delete(a.sn))}
function WS_S2C_OnMessage(a){mlog.i("[WS_S2C] on message");mlog.d("[WS_S2C] raw data: "+a.data);a=JSON.parse(a.data);if(gRequestQueue_s2c.has(a.sn))gRequestQueue_s2c.get(a.sn)(a.args),gRequestQueue_s2c.delete(a.sn);else switch(mlog.d("[WS_S2C] "+a.name),a.name){case "NotifyFocus":null!=webui.OnFocus&&(void 0!=a.args.appName?webui.OnFocus(a.args.appName):webui.OnFocus());break;case "NotifyLoseFocus":null!=webui.OnLoseFocus&&webui.OnLoseFocus();break;case "NotifyNFXTilesChanged":null!=webui.OnNFXTilesUpdate&&
webui.OnNFXTilesUpdate();break;case "NotifyLanguageChanged":null!=webui.OnLanguageChange&&webui.OnLanguageChange();break;case "NotifyNetworkChanged":null!=webui.OnNetworkChange&&webui.OnNetworkChange();break;case "NotifyUsbStorageMounted":null!=webui.OnUsbStorageMount&&webui.OnUsbStorageMount();break;case "NotifyUsbStorageUnmounted":null!=webui.OnUsbStorageUnmount&&webui.OnUsbStorageUnmount();break;default:mlog.e("[WS_S2C] received invalid command: "+a.name)}}
function WS_C2S_Connect(){mlog.i("[WS_C2S] connecting to "+gWSHost+":"+gWSPort);gWS_c2s=new WebSocket(gWSHost+":"+gWSPort,protocol_c2s);gWS_c2s.onopen=WS_C2S_OnOpen;gWS_c2s.onerror=WS_C2S_OnError;gWS_c2s.onclose=WS_C2S_OnClose;gWS_c2s.onmessage=WS_C2S_OnMessage}
function WS_S2C_Connect(){mlog.i("[WS_S2C] connecting to "+gWSHost+":"+gWSPort);gWS_s2c=new WebSocket(gWSHost+":"+gWSPort,protocol_s2c);gWS_s2c.onopen=WS_S2C_OnOpen;gWS_s2c.onerror=WS_S2C_OnError;gWS_s2c.onclose=WS_S2C_OnClose;gWS_s2c.onmessage=WS_S2C_OnMessage}
function WS_C2S_Send(a){var b=JSON.stringify({sn:gSN_c2s,name:a.name,args:a.args})+" ";switch(gWS_c2s.readyState){case WebSocket.OPEN:mlog.i("[WS_C2S] send command "+a.name);mlog.d("[WS_C2S] raw data: "+b);gWS_c2s.send(b);break;case WebSocket.CLOSE:case WebSocket.CLOSING:WS_C2S_Connect();case WebSocket.CONNECTING:mlog.w("[WS_C2S] still connecting");setTimeout(function(){WS_C2S_Send(a)},5);return}void 0!=a.callback&&gRequestQueue_c2s.set(gSN_c2s,a.callback);gSN_c2s++}
function WS_S2C_Send(a){var b=JSON.stringify({sn:gSN_s2c,name:a.name,args:a.args});switch(gWS_s2c.readyState){case WebSocket.OPEN:mlog.i("[WS_S2C] send command "+a.name);mlog.d("[WS_S2C] raw data: "+b);gWS_s2c.send(b);break;case WebSocket.CLOSE:case WebSocket.CLOSING:WS_S2C_Connect();case WebSocket.CONNECTING:mlog.w("[WS_S2C] still connecting");setTimeout(function(){WS_S2C_Send(a)},5);return}void 0!=a.callback&&gRequestQueue_s2c.set(gSN_s2c,a.callback);gSN_s2c++}
function _Init(a){gCallback=a;WS_C2S_Connect();WS_S2C_Connect();_RegisterSessionOwnerC2S(function(b){0==b.res?(mlog.d("This client to server session has been validated. Register S2C session..."),_RegisterSessionOwnerS2C(function(b){0==b.res?(mlog.d("This session has been validated. Checking API version..."),_GetApiVersion(function(b){0==b.res?(mlog.i("webui.js version: "+VERSION.major+"."+VERSION.minor),mlog.i("WebUIService version: "+b.major+"."+b.minor),b.major!=VERSION.major?(mlog.e("ERROR!!! WebUI API version mismatch with the WebUIService!"),
a(!1)):a(!0)):(mlog.e("Failed to get API version: "+webui.ErrorStrings[b.res]),a(!1))})):(mlog.e("S2C session is NOT valid!: "+webui.ErrorStrings[b.res]),a(!1))})):(mlog.e("This C2S session is NOT valid!: "+webui.ErrorStrings[b.res]),a(!1));gCallback=null})}function _GetApiVersion(a){WS_C2S_Send({name:"GetApiVersion",args:null,callback:a})}function _RegisterSessionOwnerC2S(a){WS_C2S_Send({name:"RegisterSessionOwner",args:{url:window.location.href},callback:a})}
function _RegisterSessionOwnerS2C(a){WS_S2C_Send({name:"RegisterSessionOwner",args:{url:window.location.href},callback:a})}function _OpenApp(a,b,f){WS_C2S_Send({name:"OpenApp",args:{appName:a,deepLink:b},callback:f})}function _GetAppList(a){WS_C2S_Send({name:"GetAppList",args:null,callback:a})}function _GetSourceList(a){WS_C2S_Send({name:"GetSourceList",args:null,callback:a})}function _ReturnToInputSource(a,b){WS_C2S_Send({name:"ReturnToInputSource",args:{inputSource:a},callback:b})}
function _SetInputSource(a,b){WS_C2S_Send({name:"SetInputSource",args:{inputSource:a},callback:b})}function _GetCurrentInputSource(a){WS_C2S_Send({name:"GetCurrentInputSource",args:null,callback:a})}function _GetNFXTiles(a){WS_C2S_Send({name:"GetNFXTiles",args:null,callback:a})}function _OpenNativeUI(a,b){a={name:"OpenNativeUI",args:{command:a},callback:b};WS_C2S_Send(a)}function _GetNetworkInfo(a){WS_C2S_Send({name:"GetNetworkInfo",args:null,callback:a})}
function _GetUsbInfo(a){WS_C2S_Send({name:"GetUsbInfo",args:null,callback:a})}function _Echo(a,b){WS_C2S_Send({name:"Echo",args:a,callback:b})}
var INPUTSOURCE={VGA:"vga",ATV:"atv",AV1:"av 1",AV2:"av 2",AV3:"av 3",AV4:"av 4",AV5:"av 5",AV6:"av 6",AV7:"av 7",AV8:"av 8",SVIDEO1:"s-video 1",SVIDEO2:"s-video 2",SVIDEO3:"s-video 3",SVIDEO4:"s-video 4",COMP1:"component 1",COMP2:"component 2",COMP3:"component 3",SCART1:"scart 1",SCART2:"scart 2",HDMI1:"hdmi 1",HDMI2:"hdmi 2",HDMI3:"hdmi 3",HDMI4:"hdmi 4",DTV:"dtv",DVI1:"dvi 1",DVI2:"dvi 2",DVI3:"dvi 3",DVI4:"dvi 4",AIR:"air",CABLE:"cable",DVBT:"dvbt",DVBC:"dvbc",DVBS:"dvbs",name:function(a){for(var b in this)if(a==
this[b])return b;return null}},webui={Init:_Init,GetApiVersion:_GetApiVersion,RegisterSessionOwner:_RegisterSessionOwnerC2S,OpenApp:_OpenApp,GetAppList:_GetAppList,GetSourceList:_GetSourceList,ReturnToInputSource:_ReturnToInputSource,SetInputSource:_SetInputSource,GetCurrentInputSource:_GetCurrentInputSource,GetNFXTiles:_GetNFXTiles,OpenNativeUI:_OpenNativeUI,GetNetworkInfo:_GetNetworkInfo,GetUsbInfo:_GetUsbInfo,Echo:_Echo,ErrorStrings:["OK","Invalid arguments","No resource","Timeout","Internal error"],
OnFocus:null,OnLoseFocus:null,OnNFXTilesUpdate:null,OnLanguageChange:null,OnNetworkChange:null,OnUsbStorageMount:null,OnUsbStorageUnmount:null};
